version: "3"

services:
  nginx:
    container_name: frontend
    networks:
      - d102-network
    image: ${REGISTRY}/frontend:${TAG}
    restart: always
    volumes:
      - /home/jenkins/deploy/frontend/conf.d:/etc/nginx/conf.d
    environment:
      TZ: "Asia/Seoul"

networks:
  d102-network:
    name: d102-network
    external: true