spring:
  profiles:
    active: local
    group:
      local: local, common
      prod: prod, common

---

spring:
  config:
    activate:
      on-profile: common

  # MultiPart File Upload
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

server:
  port: 8082
  servlet:
    context-path: /file

# Swagger
springdoc:
  packages-to-scan: com.d102.file.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
    info:
      title: D102 FILE Server
      description: Sweet rain fell in class 4
      version: 0.0.1
  override-with-generic-response: false
  use-fqn: true
